services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: digital_signage_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - ds_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: digital_signage_frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - ds_net

networks:
  ds_net:
    driver: bridge